; Emergency rollback to the last cross-game portal (or the initial ship save).
;
; The disabled second displayed SM slot contains the persistent randomized map
; followed by the material, non-map portions of an SM save. The disabled third
; displayed slot contains the complete shared item-buffer block. Timers,
; statistics, and explored-map data intentionally remain outside the rollback.

!SM_PORTAL_BACKUP_CAPTURING = $CAFE
!SM_PORTAL_BACKUP_VALID = $BACC

!SM_SLOT0_STATE = $400010
!SM_SLOT0_EXTRA = $400870

org sm_persistent_map_code_end

; Create a checkpoint only for the untouched initial state. This is called
; while setting up normal SM gameplay, so an existing checkpoint is not
; accidentally regenerated by a death, reset, or ordinary load.
sm_portal_checkpoint_create_initial:
	php
	rep #$30

	lda.l config_sm_map_randomization
	beq .done
	lda.l !SM_PORTAL_BACKUP_MARKER
	bne .done
	lda.l !SM_PORTAL_BACKUP_MARKER_INV
	bne .done

	plp
	jml sm_portal_checkpoint_create

.done:
	plp
	rtl

; Capture the state after the incoming portal autosave has established its
; load station. Portal arrivals always replace an older checkpoint.
sm_portal_checkpoint_create:
	php
	rep #$30
	phx
	phy

	lda.l config_sm_map_randomization
	beq .done

	lda.w #!SM_PORTAL_BACKUP_CAPTURING
	sta.l !SM_PORTAL_BACKUP_MARKER
	eor.w #$FFFF
	sta.l !SM_PORTAL_BACKUP_MARKER_INV

	ldx.w #$0000
.state_loop:
	lda.l !SM_SLOT0_STATE,x
	sta.l !SM_PORTAL_BACKUP_STATE,x
	inx
	inx
	cpx.w #!SM_PORTAL_BACKUP_STATE_SIZE
	bne .state_loop

	ldx.w #$0000
.extra_loop:
	lda.l !SM_SLOT0_EXTRA,x
	sta.l !SM_PORTAL_BACKUP_EXTRA,x
	inx
	inx
	cpx.w #!SM_PORTAL_BACKUP_EXTRA_SIZE
	bne .extra_loop

	ldx.w #$0000
.shared_loop:
	lda.l !SRAM_ITEM_BUFFER,x
	sta.l !SM_PORTAL_BACKUP_SHARED,x
	inx
	inx
	cpx.w #!SM_PORTAL_BACKUP_SHARED_SIZE
	bne .shared_loop

	ldx.w #$0000
.completion_loop:
	lda.l !SRAM_SM_COMPLETED,x
	sta.l !SM_PORTAL_BACKUP_COMPLETION,x
	inx
	inx
	cpx.w #!SM_PORTAL_BACKUP_COMPLETION_SIZE
	bne .completion_loop

	; Z1 ring delivery also writes its cosmetic tunic byte directly outside
	; the shared buffer. Store a word so every checkpoint copy stays 16-bit.
	lda.l !Z1_TunicColor
	and.w #$00FF
	sta.l !SM_PORTAL_BACKUP_Z1_TUNIC

	; Publish validity last so an interrupted capture is never restorable.
	lda.w #!SM_PORTAL_BACKUP_VALID
	sta.l !SM_PORTAL_BACKUP_MARKER
	eor.w #$FFFF
	sta.l !SM_PORTAL_BACKUP_MARKER_INV

.done:
	ply
	plx
	plp
	rtl

; Return carry set only when a map-randomizer checkpoint is complete.
sm_portal_checkpoint_is_valid:
	php
	rep #$20

	lda.l config_sm_map_randomization
	beq .invalid
	lda.l !SM_PORTAL_BACKUP_MARKER
	cmp.w #!SM_PORTAL_BACKUP_VALID
	bne .invalid
	eor.w #$FFFF
	cmp.l !SM_PORTAL_BACKUP_MARKER_INV
	bne .invalid

	plp
	sec
	rtl

.invalid:
	plp
	clc
	rtl

; Restore all material state captured at the portal. The slot-0 map block is
; deliberately untouched; LoadGame merges the independently persistent map.
; Return carry set on success.
sm_portal_checkpoint_restore:
	jsl sm_portal_checkpoint_is_valid
	bcc .invalid

	php
	rep #$30
	phx
	phy

	ldx.w #$0000
.state_loop:
	lda.l !SM_PORTAL_BACKUP_STATE,x
	sta.l !SM_SLOT0_STATE,x
	inx
	inx
	cpx.w #!SM_PORTAL_BACKUP_STATE_SIZE
	bne .state_loop

	ldx.w #$0000
.extra_loop:
	lda.l !SM_PORTAL_BACKUP_EXTRA,x
	sta.l !SM_SLOT0_EXTRA,x
	inx
	inx
	cpx.w #!SM_PORTAL_BACKUP_EXTRA_SIZE
	bne .extra_loop

	ldx.w #$0000
.shared_loop:
	lda.l !SM_PORTAL_BACKUP_SHARED,x
	sta.l !SRAM_ITEM_BUFFER,x
	inx
	inx
	cpx.w #!SM_PORTAL_BACKUP_SHARED_SIZE
	bne .shared_loop

	ldx.w #$0000
.completion_loop:
	lda.l !SM_PORTAL_BACKUP_COMPLETION,x
	sta.l !SRAM_SM_COMPLETED,x
	inx
	inx
	cpx.w #!SM_PORTAL_BACKUP_COMPLETION_SIZE
	bne .completion_loop

	sep #$20
	lda.l !SM_PORTAL_BACKUP_Z1_TUNIC
	sta.l !Z1_TunicColor
	rep #$20

	; SM is active: propagate the restored ALTTP/Z1/M1 buffers back to their
	; actual saves, using the existing checksum-aware synchronization path.
	lda.w #$0000
	jsl mb_RestoreItemBuffers
	jsl sm_fix_checksum

	ply
	plx
	plp
	sec
	rtl

.invalid:
	clc
	rtl

; The native save confirmation starts on Yes. This hook keeps native behavior
; everywhere else and starts the portal-revert prompt on No.
sm_portal_revert_init_confirmation:
	rep #$30
	stz $05F9
	lda.l !SM_PORTAL_REVERT_DIALOG_ACTIVE
	beq .done
	lda.w #$0002
	sta $05F9
.done:
	rtl

sm_portal_revert_code_end:
assert sm_portal_revert_code_end == $B5F200
warnpc $B5F800
